/*
 * Copyright (C) 2017 Hugo Dooms & Lilian Petitpas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.centralelille.ig2i.l2.IHM.vuecontroleur;

import com.centralelille.ig2i.l2.IHM.Main;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;

/**
 *
 * @author Hugo
 */
public final class Accueil extends JFrame
    {

    /**
     *
     */
    private static final long serialVersionUID = 8_724_275L;

    /**
     * Creates new form Accueil
     */
    public Accueil()
        {
        this.setLocationRelativeTo( null );
        initComponents();
        }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new JPanel();
        eltButtonNouveau = new JButton();
        eltButtonOuvrir = new JButton();
        eltButtonTutoriel = new JButton();
        jPanel2 = new JPanel();
        jLabel1 = new JLabel();
        jPanel3 = new JPanel();
        jLabel2 = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle(Main.BUNDLE.getString("main.title")); // NOI18N
        setBackground(new Color(55, 150, 202));

        jPanel1.setBackground(new Color(240, 240, 250));

        eltButtonNouveau.setBackground(new Color(255, 255, 255));
        eltButtonNouveau.setText(Main.BUNDLE.getString("accueil.nouveau")); // NOI18N
        eltButtonNouveau.setToolTipText(Main.BUNDLE.getString("accueil.nouveau.tooltip")); // NOI18N
        eltButtonNouveau.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                eltButtonNouveauActionPerformed(evt);
            }
        });

        eltButtonOuvrir.setBackground(new Color(255, 255, 255));
        eltButtonOuvrir.setText(Main.BUNDLE.getString("accueil.ouvrir")); // NOI18N
        eltButtonOuvrir.setToolTipText(Main.BUNDLE.getString("accueil.ouvrir.tooltip")); // NOI18N
        eltButtonOuvrir.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                eltButtonOuvrirActionPerformed(evt);
            }
        });

        eltButtonTutoriel.setBackground(new Color(255, 255, 255));
        eltButtonTutoriel.setText(Main.BUNDLE.getString("accueil.tutoriel")); // NOI18N
        eltButtonTutoriel.setToolTipText(Main.BUNDLE.getString("accueil.tutoriel.tooltip")); // NOI18N
        eltButtonTutoriel.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                eltButtonTutorielActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new Color(230, 230, 255));
        jPanel2.setToolTipText("null");

        jLabel1.setText(Main.BUNDLE.getString("accueil.titre")); // NOI18N
        jLabel1.setHorizontalTextPosition(SwingConstants.CENTER);

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new Color(230, 230, 255));

        jLabel2.setText(Main.BUNDLE.getString("accueil.credit")); // NOI18N

        GroupLayout jPanel3Layout = new GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(250, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(eltButtonOuvrir, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eltButtonTutoriel, GroupLayout.Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(eltButtonNouveau, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(eltButtonNouveau)
                .addGap(18, 18, 18)
                .addComponent(eltButtonOuvrir)
                .addGap(18, 18, 18)
                .addComponent(eltButtonTutoriel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eltButtonTutorielActionPerformed(ActionEvent evt)//GEN-FIRST:event_eltButtonTutorielActionPerformed
    {//GEN-HEADEREND:event_eltButtonTutorielActionPerformed
        FenetreEditeur e = new FenetreEditeur( true );
        this.dispose();
    }//GEN-LAST:event_eltButtonTutorielActionPerformed

    private void eltButtonOuvrirActionPerformed(ActionEvent evt)//GEN-FIRST:event_eltButtonOuvrirActionPerformed
    {//GEN-HEADEREND:event_eltButtonOuvrirActionPerformed
        ChoixFichier fc = new ChoixFichier();
        int returnVal = fc.showOpenDialog( this );

        if ( returnVal == JFileChooser.APPROVE_OPTION )
            {
            File file = fc.getSelectedFile();
            FenetreEditeur e = new FenetreEditeur( file );
            this.dispose();
            }
    }//GEN-LAST:event_eltButtonOuvrirActionPerformed

    private void eltButtonNouveauActionPerformed(ActionEvent evt)//GEN-FIRST:event_eltButtonNouveauActionPerformed
    {//GEN-HEADEREND:event_eltButtonNouveauActionPerformed
        FenetreEditeur e = new FenetreEditeur( false );
        this.dispose();
    }//GEN-LAST:event_eltButtonNouveauActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton eltButtonNouveau;
    private JButton eltButtonOuvrir;
    private JButton eltButtonTutoriel;
    private JLabel jLabel1;
    private JLabel jLabel2;
    private JPanel jPanel1;
    private JPanel jPanel2;
    private JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    }
