/*
 * Copyright (C) 2017 Hugo Dooms & Lilian Petitpas
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.centralelille.ig2i.l2.IHM.vuecontroleur;

import com.centralelille.ig2i.l2.IHM.Main;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;

/**
 *
 * @author Hugo
 */
public final class FenetreDCouleur extends javax.swing.JDialog
    {

    /**
     *
     */
    private static final long serialVersionUID = 1_745_698_461L;
    private FenetreEditeur reference;

    /**
     * Creates new form FenetreDCouleur
     */
    public FenetreDCouleur( FenetreEditeur parent )
        {
        super( parent, true );
        this.reference = parent;
        initComponents();
        setLocationRelativeTo( parent );
        setVisible( true );
        }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jColorChooser1 = new JColorChooser();
        jPanel1 = new JPanel();
        jLabel1 = new JLabel();
        jPanel2 = new JPanel();
        jButtonAnnulerCouleur = new JButton();
        jButtonValiderCouleur = new JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Main.BUNDLE.getString("selectcouleur.titre")); // NOI18N
        setBackground(new Color(230, 230, 255));

        jColorChooser1.setBackground(new Color(240, 240, 255));

        jPanel1.setBackground(new Color(230, 230, 250));

        jLabel1.setFont(new Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText(Main.BUNDLE.getString("selectcouleur.titre")); // NOI18N

        GroupLayout jPanel1Layout = new GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new Color(230, 230, 255));

        jButtonAnnulerCouleur.setText(Main.BUNDLE.getString("common.annuler")); // NOI18N
        jButtonAnnulerCouleur.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                jButtonAnnulerCouleurActionPerformed(evt);
            }
        });

        jButtonValiderCouleur.setText(Main.BUNDLE.getString("common.valider")); // NOI18N
        jButtonValiderCouleur.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                jButtonValiderCouleurActionPerformed(evt);
            }
        });

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAnnulerCouleur)
                .addGap(18, 18, 18)
                .addComponent(jButtonValiderCouleur)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonValiderCouleur)
                    .addComponent(jButtonAnnulerCouleur))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
            .addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jColorChooser1, GroupLayout.PREFERRED_SIZE, 235, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonValiderCouleurActionPerformed(ActionEvent evt)//GEN-FIRST:event_jButtonValiderCouleurActionPerformed
    {//GEN-HEADEREND:event_jButtonValiderCouleurActionPerformed
        this.reference.setResultatCouleur( this.jColorChooser1.getColor() );
        this.reference.setModified( true );
        this.dispose();
        this.getParent().requestFocusInWindow();
    }//GEN-LAST:event_jButtonValiderCouleurActionPerformed

    private void jButtonAnnulerCouleurActionPerformed(ActionEvent evt)//GEN-FIRST:event_jButtonAnnulerCouleurActionPerformed
    {//GEN-HEADEREND:event_jButtonAnnulerCouleurActionPerformed
        // TODO add your handling code here:
        this.dispose();
        this.getParent().requestFocusInWindow();
    }//GEN-LAST:event_jButtonAnnulerCouleurActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    JButton jButtonAnnulerCouleur;
    JButton jButtonValiderCouleur;
    JColorChooser jColorChooser1;
    JLabel jLabel1;
    JPanel jPanel1;
    JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    }
